name: Build documentation
on: [push, pull_request]
env:
  SPHINXOPTS: -W --keep going

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: pip install -r doc/requirements.txt
    - name: Build documentation
      env:
        SPHINXOPTS: -W --keep-going
      run: make html -C doc
